name: Push bluecherry-esp-idf to https://components.espressif.com
on:
  workflow_dispatch:
  push:
    tags:
      - V*
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload components
        uses: espressif/upload-components-ci-action@v1.0.5
        with:
          namespace: "bluecherry"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          name: "bluecherry"
          directories: "."
